name: Build Docker image
on:
  push:
    branches:
      - main
      - release/**
  workflow_dispatch:
jobs:
  build:
    name: Build Docker container
    runs-on: docker
    defaults:
      run:
        working-directory: ./app
    env:
      IMAGE: git.daglesia.com/magdalena/flagship-website
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -f Dockerfile -t "${IMAGE}:${IMAGE_TAG}" -t "${IMAGE}:latest" .
      - name: Push Docker image
        run: |
          docker login git.daglesia.com -u ${{ secrets.FORGEJO_USERNAME }} --password-stdin <<< "${{ secrets.PACKAGE_TOKEN }}"
          docker push "${IMAGE}:${IMAGE_TAG}"
          docker push "${IMAGE}:latest"